database:
  host: localhost
  port: 5432
  user: username
  password: password
  dbname: bookdb

paths:
  data_dir: /path/to/data
  output_dir: /path/to/output

artifacts_config:
  artifacts_dir: /path/to/artifacts

data_ingestion_config:
  dataset_download_url: https://example.com/dataset.csv
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  books_csv_file: books.csv
  ratings_csv_file: ratings.csv
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects

data_transformation_config:
  transformed_data_dir: transformed_data

model_trainer_config:
  trained_model_dir: trained_models
  trained_model_name: model.pkl

recommendation_config:
  poster_api_url: https://example.com/api/poster
